### ISSUE TITLE
The Command hub not working well.

### ISSUE THREAD

**Issue by GladdeNossoNL7** [PranavVerma-droid/AdvancedTech#24]
**Describe the bug**
The command hub is not working well. I made one recently and I put a engine on it like it asked me to. After that I made 6 of those solar panels which I tried to connect to the same command hub. But I noticed that the menu of the command hub was broken. I could only connect 1 solar pannel and I could grab the glass panes and every item which you should not be able to grab from the menu.

**To Reproduce**
1. Get a command hub, command hub engine and a solar panel. 
2. Place them next to each other and right click on the command hub.
3. You notice that you can only link 1 solar pannel and that you can grab the glass panes from the command hub gui.

**Expected behavior**
After I made tue command hub and command hub engine I expected that I could link as many solar panels to it as I wanted.
**Screenshots**
Dont have any 
**Desktop (please complete the following information):**
 - Slimefun Version [ e.g. DEV 1081]: 
 - Server Version [e.g. Paper 1.18.2]: 
 - AdvancedTech Version [e.g. DEV 10]:
We have the most recent slime fun versions.
**Additional context**

**Comment by DexterSK** [comment]
same issue, here is callstack:
```[08:39:16 ERROR]: Could not pass event InventoryDragEvent to AdvancedTech vDEV - 19 (git c133bfdd)
java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.ItemStack.hasItemMeta()" because the return value of "org.bukkit.inventory.Inventory.getItem(int)" is null
        at me.pranavverma.advancedtech.general.items.commanders.command_hub.command_hub.onInventoryDrag(command_hub.java:286) ~[SlimefunAdvancedTech.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor2885.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:git-Purpur-2023]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.1.jar:git-Purpur-2023]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.1.jar:git-Purpur-2023]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.world.inventory.AbstractContainerMenu.doClick(AbstractContainerMenu.java:480) ~[?:?]
        at net.minecraft.world.inventory.AbstractContainerMenu.clicked(AbstractContainerMenu.java:383) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3252) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.1.jar:git-Purpur-2023]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1366) ~[purpur-1.20.1.jar:git-Purpur-2023]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.20.1.jar:git-Purpur-2023]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1343) ~[purpur-1.20.1.jar:git-Purpur-2023]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1336) ~[purpur-1.20.1.jar:git-Purpur-2023]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1314) ~[purpur-1.20.1.jar:git-Purpur-2023]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202) ~[purpur-1.20.1.jar:git-Purpur-2023]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.1.jar:git-Purpur-2023]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]```

**Comment by PranavVerma-droid** [comment]
known bug, working on fixing this.
